### ISSUE TITLE
Possible bug - form_end

### ISSUE THREAD

**Issue by FourStacks** [kristijanhusak/laravel-form-builder#101]
Hi @kristijanhusak 

Not sure if this is a bug or not but would be interested to know if you're able to replicate it and if it's intended (or unavoidable) behaviour

Scenario:

I've got a list of Tags on a page.  Each Tag name is displayed in a simple unordered list element along with 2 forms 
- a edit tag form with a name (text) field, description (textarea) field, id (hidden) field and a submit button
- a delete tag form with an id (hidden) field and a submit button.

in my view, I'm grabbing the id of the current Tag that I'm iterating over and I'm dropping this id number is as the default value of the hidden field e.g.

    {!! form_start($editTagForm) !!}
    {!! form_row($editTagForm->id, ['default_value' => $tag->id]) !!}
    {!! form_end($editTagForm) !!}

    {!! form_start($deleteTagForm) !!}
    {!! form_row($deleteTagForm->id, ['default_value' => $tag->id]) !!}
    {!! form_end($deleteTagForm) !!}

This renders perfectly for the first tag in the list - both forms display as expected.  However for all subsequent forms, the form is displayed minus all fields except for the hidden id field.  All other form markup is present and correct (e.g. form is opened and closed properly and the CSRF token and PUT fields are added).

I can make these fields show up by manually adding them in on the view e.g. 
    
    {!! form_start($editTagForm) !!}
    {!! form_row($editTagForm->id, ['default_value' => $tag->id]) !!}
    {!! form_row($editTagForm->name) !!}
    {!! form_row($editTagForm->description) !!}
    {!! form_row($editTagForm->submit) !!}
    {!! form_end($editTagForm) !!}

But from what I understand of the end_form tag I probably shouldn't need to right?

**Comment by kristijanhusak** [comment]
Hi @FourStacks ,

Very interesting situation. The problem exists because once the fields are rendered (in this situation in form_end), they cannot be rerendered. I set the flag to prevent that, to avoid field duplication.

I just pushed a fix to the master branch, that fixes this issue. There is a `rebuildForm` method on the form class, which basically rebuilds the form from scratch, so you have a fresh instance. You can use it like this:

```
@foreach ($tags as $tag)
    {!! form_start($editTagForm->rebuildForm()) !!}
    {!! form_row($editTagForm->id, ['default_value' => $tag->id]) !!}
    {!! form_end($editTagForm) !!}
@endforeach
```

Let me know if it's working for you. I will not draft a release yet, because i already published one today for a more urgent fix. Will be in next release ofc.

**Comment by FourStacks** [comment]
Boom!  That's done the trick - thanks @kristijanhusak!  Wish everything in life was fixed this quickly...!

**Comment by kristijanhusak** [comment]
No problem, thanks for reporting :) Closing.
