### ISSUE TITLE
Input Error not showing correctly when rendering manually

### ISSUE THREAD

**Issue by nicozimmermann94** [kristijanhusak/laravel-form-builder#115]
Hey,
if you render a form simply by using form() and trigger an error, then a text message appears and the form input will get the error class (making the input field red).

But if you manually render the form using form_label, form_widget and form_error, only the error message will appear. Is there a way to make the input form getting red (the danger class)?

Cheers.

**Comment by kristijanhusak** [comment]
Hi,
That's strange. Will test it out. In the meantime, try using [form_row](http://kristijanhusak.github.io/laravel-form-builder/form/viewhelpers.html#form_row)

**Comment by kristijanhusak** [comment]
@nicozimmermann94 
I checked why it is not working. When you split single field with `form_label`, `form_widget`, and `form_error`, wrapper for field is not rendered by default, only those parts.

So when you call `form_row`, you get something like this:
```html
<!-- `has-error` added only if validation errors exists for this field -->
<div class="form-group has-error">
  <label for="name" class="control-label">Name</label>
  <input type="text" name="name" id="name">
  <!-- Only if validation errors exists -->
  <div class="text-danger">This field is required.</div>
</div>
```

In that case, wrapper, which is `<div class="form-group">` is rendered, and `has-error` class can be properly added to wrapper (according to http://getbootstrap.com/css/#forms-control-validation).

When you call each separately, you get this:
```
{!! form_label($form->name) !!}
<!-- renders -->
<label for="name" class="control-label">Name</label>

{!! form_widget($form->name) !!}
<!-- renders -->
<input type="text" name="name" id="name">

{!! form_errors($form->name) !!}
<!-- renders Only if validation errors exists -->
<div class="text-danger">This field is required.</div>
```

so the wrapper is never rendered, and that's why you can not have proper highlighting.

Solution to this is to use `form_row`, or publish views and update templates which by default requires rendering label and field at same time. More info [here](http://kristijanhusak.github.io/laravel-form-builder/custom/configuration-basics.html)
