### ISSUE TITLE
allow null field name and labels for static items

### ISSUE THREAD

**Issue by ceejayoz** [kristijanhusak/laravel-form-builder#154]
A common use for static fields would be adding a simple div/paragraph block of HTML, perhaps with instructions on filling out a portion of the form. Currently, it's necessary to give this block a field name it doesn't need, and while a `null` label can be provided the empty `<label>` tag is still generated.

    $this->add(null, 'static', [
        'label' => null,
        'value' => 'Foo bar.',
    ]);

should generate:

    <div class="form-control-static">Foo bar.</div>

Currently, it requires a field name and generates:

    <label class="control-label"></label>
    <div class="form-control-static" id="something" >Foo bar.</div>

**Comment by kristijanhusak** [comment]
Static type is part of regular form builder, and i cannot allow null values here.

If you need to add some message, try using `help_block` option http://kristijanhusak.github.io/laravel-form-builder/field/fieldbasics.html

**Comment by ceejayoz** [comment]
What about adding a 'html'  type or something for simple HTML blocks? `help_block` is great for stuff that's specific to a field, but I'm talking about things like (as an example) a `<h1>` header injected between logical groups of fields.

**Comment by kristijanhusak** [comment]
It's hard to fit every situation with `form($form`) only, so that's why i created `form_row` , and some other view helpers so you can split your form however needed. You can find more info here http://kristijanhusak.github.io/laravel-form-builder/form/viewhelpers.html

**Comment by ceejayoz** [comment]
Sounds like you're pretty opposed to the idea. I'm aware of the helpers - it'd just be nice (and I'd imagine a fairly common use case) not to have get that complex just to add a header row in the middle of a fairly simple form. Your project, though, so I'll go ahead and close this.

**Comment by kristijanhusak** [comment]
Yeah, I am. There were requests like yours, and i understand that, but goal is to have form builder, not html builder. I cannot treat static html like `<h1>Someting</h1` as form field. Static type is exception because it can be used to print value of the model field, which can be useful in many cases on edit forms.

There is option for every developer to extend the functionality with some custom fields. You can in a pretty simple way add your custom field which will handle stuff like this. Short explanation can be found here http://kristijanhusak.github.io/laravel-form-builder/custom/customfields.html.
