### ISSUE TITLE
Difference between setModel and model in options?

### ISSUE THREAD

**Issue by SpadXIII** [kristijanhusak/laravel-form-builder#188]
I just installed version 1.6.31 in a default laravel 5.1 download.
In my controller I build 2 forms like this:
```
        $form = $this->form(CatForm::class, [
            'model' => $cat,
        ]);

        $form2 = $this->form(CatForm::class)
            ->setModel($cat);
```

When $form is rendered, the fields have values, but for $form2, the fields are empty.

I'm still digging through the source, but haven't found why or how it is not working (yet?).

**Comment by kristijanhusak** [comment]
2nd form is using a setter, where 1st is passing it as an option when creating.

Problem with 2nd is that fields are already created and values are bound before `setModel` is called, so form needs to be rebuild with new model. Solution for that is to call `->rebuildForm()` after `setModel`:

```php
   $form2 = $this->form(CatForm::class)
            ->setModel($cat)
            ->rebuildForm();
```

I would recommend to stick with **1st solution**, because i'm planning to slowly deprecate `setModel` mostly because of this issue.

**Comment by kristijanhusak** [comment]
@SpadXIII I fixed it on master branch, but also added deprecated notice in docblock. If you want u can update. Thanks for reporting.
