### ISSUE TITLE
[Laravel 5] [Request] Method Injection

### ISSUE THREAD

**Issue by JoeHabacker** [kristijanhusak/laravel-form-builder#19]
How do you feel about setting it up so that we can inject the form directly into the controller method and bypass the FormBuilder::create() call? It looks like the main thing that would need to be changed is passing the FormHelper into the Form constructor rather than setting it after initialization, unless I'm overlooking something.

I could try to make the changes and do a pull request, but I'm quite new to this whole thing and really don't have a clue about what I'm doing when it comes to contributing.

**Comment by stevebauman** [comment]
I just started using the package today (amazing by the way!), but this can be easily bypassed by using a `BaseController` which all of your controllers extend from and adding a `createForm` method in it that all of the child controllers can use.

I think this is a good solution since you wouldn't be injecting a static namespace into each method that requires it. If you needed to change the form builder you'd only need to change the single method on the `BaseController`

**Comment by kristijanhusak** [comment]
@stevebauman 
You can inject FormBuilder into the constructor or method, and it will be pulled out of IoC container. Check [here](https://github.com/kristijanhusak/laravel-form-builder#usage-in-controllers).
