### ISSUE TITLE
_Token 

### ISSUE THREAD

**Issue by gmagnai** [kristijanhusak/laravel-form-builder#260]
Hello im using Laravel 5.2.41 and Form builder. 

But store function returns :

MassAssignmentException in Model.php line 452:
_token

in rendered HTML form have csrf token "><input name="_token" type="hidden" value="hB5tscMdSod6ZeXHFsyjLKQZOmcEYENPWT54P8Ws">"

```
    public function buildForm()
    {
        $this->category = new NewsCategory;
        $categories = array();
        foreach($this->category->all() as $category){
            $categories[] = [$category->id=>$category->name];
        }

        $this
            ->add('title', 'text', ['label' => 'Мэдээллийн гарчиг'])
            ->add('image[]', 'file', ['label' => 'Зураг'])
            ->add('add image', 'button', ['label' => 'Зураг нэмэх', 'class' => 'add-image'])
            ->add('category_id', 'select', ['label' => 'Мэдээллийн ангилал', 'empty_value' => '--- Сонгох ---', 'choices' => $categories])
            ->add('content', 'textarea', ['label' => 'Мэдээллийн агуулга'])
            ->add('submit', 'submit', ['label' => 'Хадгалах']);
    }
```

Is there any problem?

**Comment by koenvu** [comment]
What is probably happening is you are using something like `$model->update($request->all());` or `new YourModel($request->all());`. The request also contain's the `_token` field used for CSRF protection. Since you have no `$fillable` or `$guarded` property on your model you may not "mass assign" properties on it. Read up on Mass assignment here: https://laravel.com/docs/5.2/eloquent#mass-assignment

It's hard for me to say without seeing the code that is triggering the update on your model. The code you showed is building the form, not handling the form, from the looks of it.

Hope that helps a bit!

**Comment by gmagnai** [comment]
Oh.. I have no $fillable.
Thank you! I'll try it.
