### ISSUE TITLE
5.5 Compatible

### ISSUE THREAD

**Issue by montyclt** [kristijanhusak/laravel-form-builder#397]
Hello! 😘 

I found two problems in Laravel 5.5

- `RuleParser` doesn't accept Rule objects.
- `FormBuilder` is using `fire` method of `Illuminate\Contracts\Events\Dispatcher` that was renamed to `dispatch` in 5.4.

I don't know if there are more incompatibilities, if any can help us [searching it](https://laravel.com/docs/5.5/upgrade), we can submit a PR. I propose create a new branch to send these PR with a new composer label, and don't break public API of people that are using previous version of Laravel.

**Comment by kristijanhusak** [comment]
Hi @montyclt ,

yeah, `RuleParser` cannot be used. It needs to be added.

For the `fire` method, as i see in the source code of the laravel events [here](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Events/Dispatcher.php#L170), it still exists and can be used, but we should definitely do something because the contract does not have it.
I guess we will need to wrap the `fire` method call in some check.

As i can see, nothing else needs to be changed. If you find something, let me know.

Also i would appreciate if you could contribute for this, since i don't have time lately to work on this.

**Comment by nekromoff** [comment]
confirming incompatibility with Laravel 5.8

**Comment by kristijanhusak** [comment]
fire method was changed to dispatch in latest version.
