### ISSUE TITLE
[Laravel 5]  wrapper for each field in collection

### ISSUE THREAD

**Issue by jaroslawziolkowski** [kristijanhusak/laravel-form-builder#51]
If is possible use "choice, expanded=>true, multiple=>true"
We can add wrapper for all fields. How can we make wrapper for each label with checkbox field?

for example we would like add div or span as wrapper
```
<div class="general_wrapper_from_config">
<div class="wrapper">
<label for="x"><input type="checkbox"> Label text </label>
</div>

<div class="wrapper">
<label for="xy"><input type="checkbox"> Label text </label>
</div>
</div>
```

**Comment by kristijanhusak** [comment]
There are 2 ways to handle this:
By passing custom template to the field like this:
```php
```

**Comment by jaroslawziolkowski** [comment]
Your code block is empty :)

**Comment by kristijanhusak** [comment]
Yea i pressed ctrl enter accidentally. Updated it.

**Comment by kristijanhusak** [comment]
There is also one more way. In the view you can do this:

```
foreach ($choiceField->getChildren() as $child) {
    <div class="wrapper">
        {!! form_row($child) !!}
    </div>
}
```

If you are changing `checkbox.php` just remove check `$options['is_child']` and it will work.

Hope i helped.

**Comment by kristijanhusak** [comment]
Did you manage to set it up?

**Comment by jaroslawziolkowski** [comment]
I my case (small form) I user view solution and works. But to bigger forms I'm sure that I will change templates

**Comment by kristijanhusak** [comment]
I will probably add an option to modify each choice field options separately, so it will be possible to add configuration like this. Will let you know when it's added so you can clean up your code.

**Comment by kristijanhusak** [comment]
@jaroslawziolkowski 
I added support for this. Check the docs [here](https://github.com/kristijanhusak/laravel-form-builder#field-customization), `bio` and `gender` fields.
If you do not need wrapper at all, you can set it to `false`, for any field.
If you have choice with checkboxes or radios, you can set their options with `choice_options` like in `gender` field in the readme. Default for wrapper is false, because of BC.
When `choice` field generates select (expanded option is false), options are read from the main options, not `choice_options`.
Just do a composer update, and republish the views.

**Comment by jaroslawziolkowski** [comment]
@kristijanhusak 
Great news, thank you :)
