### ISSUE TITLE
count($currentInput) throws error when $currentInput is null

### ISSUE THREAD

**Issue by kmbt** [kristijanhusak/laravel-form-builder#515]
`count($currentInput)` throws error when `$currentInput` is null

https://github.com/kristijanhusak/laravel-form-builder/blob/bebd624157caf5287883b768e6c0260c47f4d3b5/src/Kris/LaravelFormBuilder/Fields/CollectionType.php#L99

This happens when the form is initialized with no request input and `prefer_input` option is set to true.

I suppose that there should be an additional check in this condition for $currentInput not being null. Posiibly like:
```
elseif ($this->getOption('prefer_input') && !is_null($currentInput) && count($currentInput)) {
```

**Comment by rudiedirkx** [comment]
Aw man I thought I'd tested all use cases. Good point. But instead of an `is_null()` check, maybe we should force `$currentInput` to be an array. If it isn't, it's not valid input (since it's a collection), and it's `[]`. So `count()` will always work, and it's always an array.

You want to try a PR?

**Comment by kmbt** [comment]
Hi :) Recently I've been having a lot of work and I am not sure when (or if) I would be able to do this PR in the near future.

**Comment by kmbt** [comment]
Do you think that this would be ok?

https://github.com/kmbt/laravel-form-builder/blob/202c7767cadea0228220d51d18c4fae6a2225e13/src/Kris/LaravelFormBuilder/Fields/CollectionType.php#L81

In my case it seems to work fine.

**Comment by rudiedirkx** [comment]
That's probably good enough, but what if the client cheats and sends a string? That's an error, and not a nice catchable one, but a php error.

**Comment by kmbt** [comment]
Are you sure about that? We seem to have a check here.

https://github.com/kmbt/laravel-form-builder/blob/202c7767cadea0228220d51d18c4fae6a2225e13/src/Kris/LaravelFormBuilder/Fields/CollectionType.php#L127-L131

**Comment by rudiedirkx** [comment]
Yes, that's too late. This issue is about the `count($currentInput)`, which is where it'll still go wrong if the client cheats. We have to make sure data/input is an array before that. If it's not, someone's cheating, so we can just ignore the input and use `[]`. The nice error is necessary for the collection data. The request input doesn't need a nice error, just not an unhandled php error.

But that's an edge case. If a client cheats like that, it's not broken, it just fails dirtily. The most important is that there's no error without the cheating =) Your simple solution is good enough for that. Sorry for all the chattering.
