### ISSUE TITLE
`getFieldValues()` won't collect newly added item of `CollectionType` field.

### ISSUE THREAD

**Issue by yaquawa** [kristijanhusak/laravel-form-builder#573]
I think I found a serious bug of this package.

I've created a form which has a collection of child form by following the instruction of the docs here: http://kristijanhusak.github.io/laravel-form-builder/field/collection.html#collection-of-child-forms

The problem is that the newly added "tags" can not be collected by the `$form->getFieldValues()` method. Similarly `$form->getRules()` method won't get the rules for the newly added "tags" too, which means validation won't work correctly. Is this intended behavior or it's a bug?

I think this is a bug similar to #476

## Workaround
I found the answer myself at [here](https://github.com/kristijanhusak/laravel-form-builder/issues/464#issuecomment-499516016).

> set the `prefer_input=true` option on the collection, and the POST data will be used as a base, not the form's collection items.

I think adding this piece of description to the docs maybe helpful 😃

**Comment by rudiedirkx** [comment]
I don't think it's a bug at all. The server is responsible for what should be validated, not the client. So the server should make the POST (for validation) form exactly the same as the GET (for input) form. You don't want to make the cheating hacking client the boss of input.

Adding that AND option `prefer_input` to the docs would be a very good idea. Please PR please, because I don't have time to think about this now.

**Comment by yaquawa** [comment]
> The server is responsible for what should be validated, not the client.

Understanded, Thanks!

**Comment by rudiedirkx** [comment]
Sometimes you need `prefer_input` though. If you can add/delete records with JS, and send them, the client IS (partly) responsible for what should be validated.
