### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable - Laravel 8.0

### ISSUE THREAD

**Issue by superlogicabrunocosta** [kristijanhusak/laravel-form-builder#620]
count(): Parameter must be an array or an object that implements Countable

![image](https://user-images.githubusercontent.com/59574132/94066270-a01d9f00-fdc2-11ea-8bb2-864097935f9b.png)

**Comment by rudiedirkx** [comment]
We need much more context than a screenshot if you want us to help. I'm afraid you'll have to debug it. Where does this non-countable value come from? How do you create the form in the controller? With what data? What's the POST data? Etc.

**Comment by superlogicabrunocosta** [comment]
Então, eu tenho dois formularios, um deles chama o outro via coleção, porem quando eu tenho dados o mesmo da esse erro. Criei um repositorio com esse simples teste para dar uma olhada

https://github.com/bhcosta90/laravel-8.git

**Comment by superlogicabrunocosta** [comment]
So, I have two forms, one of them calls the other via collection, however when I have data the same as this error. I created a repository with this simple test to take a look

https://github.com/bhcosta90/laravel-8.git

**Comment by rudiedirkx** [comment]
Ooh, an entire repo for reproduction. Interesting.

----

It's a bug in `FormField::setupValue()`. `$attributeName` is `id` instead of `emails`, so it takes the data/model's `id` as value (`1`, not countable), instead of the `emails` property, which is a list.

My fault in #598 and later with [typical famous last words](https://github.com/kristijanhusak/laravel-form-builder/pull/599#issuecomment-633106973). I'm ashamed. I should have tested that. And/or we're missing tests...

A workaround for now is very simple. Add `'property' => 'emails',` to the collection field settings (first level, not in `'options'`).

Real fix later. Or you can take a shot at it, but try not to break #598.

**Comment by rudiedirkx** [comment]
Bug details and fix and discussion in #621
