### ISSUE TITLE
alterFieldValues in collection forms

### ISSUE THREAD

**Issue by rudiedirkx** [kristijanhusak/laravel-form-builder#675]
`alterFieldValues()` is only called for subforms if it's a `form`, not if it's inside a `collection` with type `form`.

PR later.

**Comment by rjp-thijs** [comment]
It seems that this PR is BC breaking sadly. We've had crashes on production due to a response being different then expected. Noticed there was also a Issue open for this: https://github.com/kristijanhusak/laravel-form-builder/issues/686

I tried figuring out why this happens, but it seems that the alterFieldValues requires and sets an array; while for the choise options this has always been a string.
