### ISSUE TITLE
2 columns solution

### ISSUE THREAD

**Issue by robsoncombr** [kristijanhusak/laravel-form-builder#72]
Hello,

Anyone has implemented a 2 columns solution with this?

Instead of we get 1 field per line we would get 2 fields per line.

Thank you,

Robson

**Comment by kristijanhusak** [comment]
Hi @robsoncombr ,
You can split form in view with `form_row` and set it up as you want, or create a custom template. Purpose of package is not to have ideally structured html forms, because it's impossible to fit everyone's needs, someone wants 2 columns, someone 3, etc.

Check this section in readme for more help. https://github.com/kristijanhusak/laravel-form-builder#usage-in-views
