### ISSUE TITLE
Duplicate [] added to choid choice field

### ISSUE THREAD

**Issue by hackel** [kristijanhusak/laravel-form-builder#88]
I've added a collection of child forms, and my child form contains a choice field with multiple=true.  When the field gets rendered, [] gets appended to the name twice, once in ChoiceType::createChildren, and again in FormField::prepareOptions.  This was giving me names like `contacts[0][type][][]`, thereby adding all the selections one level too deep.

~~To solve it, I just added a simple check in FormField::prepareOptions:~~
```php
if ($this->getOption('attr.multiple') && !$options['is_child']) {
    $this->name = $this->name.'[]';
}
```
~~I wasn't sure if this would cause any other side-effects, however.  Is this better than checking within ChoiceType?~~

Edit: This was a bad idea, as it prevented standard, non-child multi-selects from having the [] added.

**Comment by hackel** [comment]
~~To solve it, I just added a simple check in FormField::prepareOptions:~~
```php
if ($this->getOption('attr.multiple') && !$options['is_child']) {
    $this->name = $this->name.'[]';
}
```
~~I wasn't sure if this would cause any other side-effects, however.  Is this better than checking within ChoiceType?~~

This was a bad idea, as it prevented standard, non-child multi-selects from having the [] added.

**Comment by hackel** [comment]
Setting `$fieldMultiple=''` in ChoiceType::createChildren() seems to have solved my issue for now, but I assume that was added for a reason, so it's probably going to affect something else.

**Comment by kristijanhusak** [comment]
Thanks for reporting, I'll check it out and get back to you soon.

**Comment by kristijanhusak** [comment]
@hackel 
It should be fixed in the latest release (1.4.21). Please test it out and close issue if it works.

**Comment by FourStacks** [comment]
Hi @kristijanhusak 

I *think* this might have caused an issue when using checkbox (and presumeably other multi select) field in a child form.  Here's my scenario:

I have a a parent registration form that pulls in a few different child forms.  Example extract:

    ->add('build_location','form',[
        'class' => BuilderRegistrationCustomLocationsForm::class,
        'data' => [
            'locations' => $locations,
            'user' => $this->model
        ],
        'label' => false
    ]);

In turn, the child form displays a checkbox list that has it's choices built dynamically from the $locations variable that the parent form passed.  Extract:

    $this
        ->add('locations', 'choice', [
            'choices' => $locations,
            'expanded' => true,
            'selected' => $user->locations,
            'multiple' => true,
            'choice_options' => [
                'wrapper' => ['class' => 'checkbox']
            ]
    ]);

This all renders as expected and if the user has any locations set already they are pre populated as expected.

However, when I dd the input after submitting the form I see only one item in the locations array - here's the output:

    "build_location" => array:1 [
        "locations" => "location_1"
    ]

This is due to the fact that each of the checkbox inputs generated have the name:  build_location[locations] as opposed to build_location[locations][].  If I manually add these in using chrome dev tools I get the input in an array as expected:

    "build_location" => array:1 [
        "locations" => array:3 [
          0 => "location_2"
          1 => "location_3"
          2 => "location_5"
        ]
    ]

Have a feeling this might be related to the recent fix described above but I can't be certain (unless of course I've done something daft but I can't see any issues in my setup.

**Comment by FourStacks** [comment]
Actually, it's looking more like it's a definite bug in 1.4.21 as even a regular checkbox field in a standard form (i.e. not a child form) is also missing the brackets from the name attribute of each checkbox input.  So this:

    $this
        ->add('something', 'choice', [
            'choices' => ['x' => 'X', 'y' => 'Y', 'z' => 'Z'],
            'expanded' => true,
            'multiple' => true,
            'choice_options' => [
                'wrapper' => ['class' => 'checkbox']
            ]
        ]);

Produces this markup:

    <div class="form-group">
    
        <label for="something[]" class="control-label">Something</label>    
        
        <div class="checkbox">
            <input id="X_x" name="something" type="checkbox" value="x">    
            <label class="control-label" for="X_x">X</label>
        </div>
        <div class="checkbox">
            <input id="Y_y" name="something" type="checkbox" value="y">    
            <label class="control-label" for="Y_y">Y</label>
        </div>
        <div class="checkbox">
            <input id="Z_z" name="something" type="checkbox" value="z">    
            <label class="control-label" for="Z_z">Z</label>
        </div>
    </div>

**Comment by kristijanhusak** [comment]
@FourStacks you are right, I did a quick fix. Do a composer update, it should be working now. If not, let me know.

**Comment by FourStacks** [comment]
Works like a charm - thanks again for the speedy response!

**Comment by kristijanhusak** [comment]
Great! Thanks for reporting. Closing this.
